# Generated by Django 4.1.3 on 2023-01-07 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinematography', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('watch', 'I will watch'), ('looking', "I'm looking"), ('Viewed', 'Viewed'), ('Favourite', 'Favourite')], default=None, max_length=32)),
                ('id_cinema', models.ManyToManyField(to='cinematography.manga')),
                ('id_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
