# Generated by Django 4.1.3 on 2023-01-17 00:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name ')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Manga', 'Manga'), ('Manhua', 'Manhua'), ('Manhwa', 'Manhwa'), ('Comics', 'Comics'), ('Other', 'Other')], max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counts', models.CharField(max_length=200, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genr', models.CharField(max_length=100, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Tegs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teg', models.CharField(max_length=100, verbose_name='Teg')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_manga', models.CharField(max_length=100, verbose_name='name_manga')),
                ('name_original', models.CharField(blank=True, max_length=100, verbose_name='name_original')),
                ('time_prod', models.DateTimeField(default=datetime.datetime(2023, 1, 17, 1, 59, 25, 710129), verbose_name='time of production')),
                ('review', models.TextField(max_length=500)),
                ('avatar', models.ImageField(blank=True, default='default/none_avatar.png/', upload_to='static/images/avatars/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/products/miniava')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ManyToManyField(related_name='actors', to='product.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.categorys')),
                ('counts', models.ManyToManyField(related_name='country', to='product.country')),
                ('genre', models.ManyToManyField(related_name='genre', to='product.genre')),
                ('tegs', models.ManyToManyField(related_name='tegs', to='product.tegs')),
            ],
        ),
        migrations.CreateModel(
            name='Glawa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.FloatField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('time_prod', models.DateTimeField(default=datetime.datetime(2023, 1, 17, 1, 59, 25, 710129), verbose_name='time of production')),
                ('slug', models.SlugField(unique=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glaws', to='product.manga')),
            ],
            options={
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/images/gallery/')),
                ('glawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='product.glawa')),
            ],
        ),
    ]
